const countries = [
    {
        name: 'Afghanistan',
        code: 'af'
    },
    {
        name: 'Albania',
        code: 'al'
    },
    {
        name: 'Algeria',
        code: 'dz'
    },
    {
        name: 'Andorra',
        code: 'ad'
    },
    {
        name: 'Angola',
        code: 'ao'
    },
    {
        name: 'Anguilla',
        code: 'ai'
    },
    {
        name: 'Antigua and Barbuda',
        code: 'ag'
    },
    {
        name: 'Argentina',
        code: 'ar'
    },
    {
        name: 'Armenia',
        code: 'am'
    },
    {
        name: 'Aruba',
        code: 'aw'
    },
    {
        name: 'Australia',
        code: 'au'
    },
    {
        name: 'Austria',
        code: 'at'
    },
    {
        name: 'Azerbaijan',
        code: 'az'
    }
];

const states = {
    af: [
        'Badakhshan',
        'Badghis',
        'Balkh',
        'Daykundi Province',
        'Farah',
        'Faryab Province',
        'Helmand',
        'Herat',
        'Kandahar',
        'Kunduz',
        'Nangarhar',
        'Panjshir',
        'Parwan',
        'Samangan',
        'Sar-e Pul',
        'Uruzgan',
        'Velayat-e Khowst',
        'Velayat-e Nurestan',
        'Wardak',
        'Wilayat-e Baghlan',
        'Wilayat-e Bamyan',
        'Wilayat-e Ghazni',
        'Wilayat-e Ghor',
        'Wilayat-e Jowzjan',
        'Wilayat-e Kabul',
        'Wilayat-e Kapisa',
        'Wilayat-e Kunar',
        'Wilayat-e Laghman',
        'Wilayat-e Logar',
        'Wilayat-e Nimroz',
        'Wilayat-e Paktika',
        'Wilayat-e Paktiya',
        'Wilayat-e Takhar',
        'Wilayat-e Zabul',
    ],
    al: [
        'Qarku i Beratit',
        'Qarku i Dibres',
        'Qarku i Durresit',
        'Qarku i Elbasanit',
        'Qarku i Fierit',
        'Qarku i Gjirokastres',
        'Qarku i Korces',
        'Qarku i Kukesit',
        'Qarku i Lezhes',
        'Qarku i Shkodres',
        'Qarku i Tiranes',
        'Qarku i Vlores',
    ],
    dz: [
        'Adrar',
        'Annaba',
        'El Bayadh',
        'El Oued',
        'El Tarf',
        'Illizi',
        'Oran',
        'Oum el Bouaghi',
        "Wilaya d' Alger",
        'Wilaya de Ain Defla',
        'Wilaya de Ain Temouchent',
        'Wilaya de Batna',
        'Wilaya de Bechar',
        'Wilaya de Bejaia',
        'Wilaya de Biskra',
        'Wilaya de Blida',
        'Wilaya de Bordj Bou Arreridj',
        'Wilaya de Bouira',
        'Wilaya de Boumerdes',
        'Wilaya de Chlef',
        'Wilaya de Constantine',
        'Wilaya de Djelfa',
        'Wilaya de Ghardaia',
        'Wilaya de Guelma',
        'Wilaya de Jijel',
        'Wilaya de Khenchela',
        'Wilaya de Laghouat',
        "Wilaya de M'Sila",
        'Wilaya de Mascara',
        'Wilaya de Medea',
        'Wilaya de Mila',
        'Wilaya de Mostaganem',
        'Wilaya de Naama',
        'Wilaya de Ouargla',
        'Wilaya de Relizane',
        'Wilaya de Saida',
        'Wilaya de Setif',
        'Wilaya de Sidi Bel Abbes',
        'Wilaya de Skikda',
        'Wilaya de Souk Ahras',
        'Wilaya de Tamanrasset',
        'Wilaya de Tebessa',
        'Wilaya de Tiaret',
        'Wilaya de Tindouf',
        'Wilaya de Tipaza',
        'Wilaya de Tissemsilt',
        'Wilaya de Tizi Ouzo',
        'Wilaya de Tlemcen',
    ],
    ad: [
        'Andorra la Vella',
        'Canillo',
        'Encamp',
        'Escaldes-Engordany',
        'La Massana',
        'Ordino',
        'Sant Julia de Loria'],
    ao: [
        'Bengo Province',
        'Benguela',
        'Cabinda',
        'Cuanza Norte Province',
        'Cunene Province',
        'Huambo',
        'Huila Province',
        'Kuando Kubango',
        'Kwanza Sul',
        'Luanda Province',
        'Lunda Norte Province',
        'Lunda Sul',
        'Malanje Province',
        'Moxico',
        'Namibe Province',
        'Provincia do Bie',
        'Provincia do Uige',
        'Zaire',
    ],
    ai: [
        'Blowing Point',
        'East End',
        'George Hill',
        'Island Harbour',
        'North Hill',
        'North Side',
        'Sandy Ground',
        'Sandy Hill',
        'South Hill',
        'Stoney Ground',
        'The Farrington',
        'The Quarter',
        'The Valley',
        'West End',
    ],
    ag: [
        'Barbuda',
        'Parish of Saint George',
        'Parish of Saint John',
        'Parish of Saint Mary',
        'Parish of Saint Paul',
        'Parish of Saint Peter',
        'Parish of Saint Philip',
        'Redonda',
    ],
    ar: [
        'Catamarca Province',
        'Chaco Province',
        'Chubut Province',
        'Ciudad Autonoma de Buenos Aires',
        'Cordoba Province',
        'Corrientes Province',
        'Entre Rios Province',
        'Formosa Province',
        'Jujuy Province',
        'La Pampa Province',
        'La Rioja Province',
        'Mendoza Province',
        'Misiones Province',
        'Neuquen Province',
        'Provincia de Buenos Aires',
        'Rio Negro Province',
        'Salta Province',
        'San Juan Province',
        'San Luis Province',
        'Santa Cruz Province',
        'Santa Fe Province',
        'Santiago del Estero Province',
        'Tierra del Fuego Province',
        'Tucuman Province',
    ],
    am: [
        'Aragatsotni Marz',
        'Ararati Marz',
        'Armaviri Marz',
        "Geghark'unik'i Marz",
        "Kotayk'i Marz",
        'Lorru Marz',
        'Shiraki Marz',
        "Syunik'i Marz",
        'Tavushi Marz',
        "Vayots' Dzor",
        'Yerevan',
    ],
    aw: [

    ],
    au: [
        'Australian Capital Territory',
        'Northern Territory',
        'New South Wales',
        'Queensland',
        'South Australia',
        'Tasmania',
        'Victoria',
        'Western Australia',
    ],
    at: [
        'Burgenland',
        'Kaernten',
        'Niederoesterreich',
        'Oberoesterreich',
        'Salzburg',
        'Steiermark',
        'Tirol',
        'Vorarlberg',
        'Wien',
    ],
    az: [
        'Absheron Rayon',
        'Aghdam Rayon',
        'Aghdash Rayon',
        'Aghjabadi Rayon',
        'Aghstafa Rayon',
        'Aghsu Rayon',
        'Astara District',
        'Baku City',
        'Balakan Rayon',
        'Barda Rayon',
        'Beylagan Rayon',
        'Bilasuvar Rayon',
        'Dashkasan Rayon',
        'Fizuli Rayon',
        'Gadabay Rayon',
        'Ganja City',
        'Gobustan Rayon',
        'Goranboy Rayon',
        'Goychay Rayon',
        'Goygol Rayon',
        'Hajigabul Rayon',
        'Imishli Rayon',
        'Ismayilli Rayon',
        'Jabrayil District',
        'Jalilabad',
        'Kalbajar District',
        'Khachmaz Rayon',
        'Khizi Rayon',
        'Khojavend District',
        'Kurdamir Rayon',
        'Lacin Rayon',
        'Lankaran Rayon',
        'Lankaran Sahari',
        'Lerik Rayon',
        'Masally District',
        'Mingacevir City',
        'Naftalan City',
        'Nakhchivan',
        'Nakhchivan Autonomous Republic',
        'Neftchala Rayon',
        'Oghuz Rayon',
        'Qabala Rayon',
        'Qakh Rayon',
        'Qazakh Rayon',
        'Quba Rayon',
        'Qubadli Rayon',
        'Qusar Rayon',
        'Saatly Rayon',
        'Sabirabad Rayon',
        'Salyan Rayon',
        'Samukh Rayon',
        'Shabran Rayon',
        'Shaki city',
        'Shaki Rayon',
        'Shamakhi Rayon',
        'Shamkir Rayon',
        'Shirvan',
        'Shusha',
        'Siazan Rayon',
        'Sumqayit City',
        'Susa Rayon',
        'Tartar Rayon',
        'Tovuz Rayon',
        'Ujar Rayon',
        'Xankandi Sahari',
        'Xocali Rayon',
        'Yardymli Rayon',
        'Yevlakh City',
        'Yevlakh Rayon',
        'Zangilan Rayon',
        'Zaqatala Rayon',
        'Zardab Rayon',
    ]
};

module.exports = {
    getStatesOfFirstCountry: function () {
        return states[Object.keys(states)[0]];
    },
    getStates: function (code) {
        return states[code];
    }
    // addCountry: function (countryName, code) {
    //     let pair = {
    //         name: countryName,
    //         code: code
    //     };
    //     if(!countries.some(obj => {
    //         return obj.country === countryName && obj.code === code;
    //     })){
    //         countries.push(pair);
    //     }
    // },
    // addState: function (stateName, code){
    //     if(code in Object.keys(states)){
    //         states.code.push(stateName);
    //     }else{
    //         states[code] = stateName;
    //     }
    // }
}